name: ec2 deployment

on:
  push:
    - main
  pull_request:
    - main

jobs:
  ec2_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply --auto-approve